"use server";

import { ratelimit } from "@/lib/rate-limit";
import { loadResource } from "@/sanity/loader/loadQuery";
import { JWT } from "google-auth-library";
import {
  GoogleSpreadsheet,
  GoogleSpreadsheetWorksheet,
} from "google-spreadsheet";
import { headers } from "next/headers";
import * as z from "zod"; // 1.2 kB

// const DownloadResourceForm = v.object({
//   email: v.pipe(v.string(), v.email(), v.minLength(1), v.maxLength(250)),
//   name: v.pipe(v.string(), v.minLength(1), v.maxLength(100)),
//   resourceSlug: v.string(),
// });

const DownloadResourceForm = z.object({
  email: z.string().email().min(1).max(250),
  name: z.string().min(1).max(100),
  resourceSlug: z.string(),
});

const log = {
  ingest: async (data: any) => {
    console.log(data);
  },
};

enum STATUS_LOG {
  success = "success",
  error = "error",
}

const GOOGLE_SHEET_KEY = process.env
  .GOOGLE_SHEET_KEY!.split(String.raw`\n`)
  .join("\n");

const GOOGLE_SHEET_ID = process.env.GOOGLE_SHEET_ID!;
const GOOGLE_EMAIL = process.env.GOOGLE_EMAIL!;

const HEADERS_ROW = ["Nombre", "Correo", "Fecha", "Resource"];

function getServiceAccount() {
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: GOOGLE_EMAIL,
    key: GOOGLE_SHEET_KEY.replace('"', "").replaceAll("\n", "\n"),
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
  });

  return serviceAccountAuth;
}

async function getOrCreateHeaderRow(sheet: GoogleSpreadsheetWorksheet) {
  await sheet.loadHeaderRow();

  await sheet.setHeaderRow(HEADERS_ROW);
}

async function getOrCreateSheet(sheetName: string) {
  const serviceAccountAuth = getServiceAccount();
  const doc = new GoogleSpreadsheet(GOOGLE_SHEET_ID, serviceAccountAuth);

  await doc.loadInfo();

  const sheet =
    doc.sheetsByTitle[sheetName] ||
    (await doc.addSheet({
      title: sheetName,
      headerValues: HEADERS_ROW,
    }));

  await getOrCreateHeaderRow(sheet);

  return sheet;
}

function mapContact(data: z.infer<typeof DownloadResourceForm>) {
  return {
    [HEADERS_ROW[0]]: data.name,
    [HEADERS_ROW[1]]: data.email,
    [HEADERS_ROW[3]]: data.resourceSlug,
    [HEADERS_ROW[2]]: new Date().toLocaleDateString(),
  };
}

async function findContact(sheet: GoogleSpreadsheetWorksheet, email: string) {
  const rows = await sheet.getRows();

  return rows.find((row) => row.get(HEADERS_ROW[1]) === email);
}

export async function downloadResource(
  _: {
    success: boolean;
    error: any;
    url?: string;
  },
  formData: FormData,
) {
  try {
    const ip =
      headers().get("x-real-ip") ||
      headers().get("x-forwarded-for") ||
      "127.0.0.1";
    const { success, limit, reset, remaining } = await ratelimit.limit(ip);

    if (!success) {
      log.ingest({
        event: "ratelimit",
        data: {
          limit,
          reset,
          remaining,
        },
        status_log: STATUS_LOG.error,
      });

      return {
        success: false,
        error: "Too many requests",
      };
    }

    log.ingest({
      event: "ratelimit",
      data: {
        limit,
        reset,
        remaining,
      },
      status_log: STATUS_LOG.success,
    });

    const name = formData.get("name") as string;

    const email = formData.get("email") as string;

    const resourceSlug = formData.get("resourceSlug") as string;

    const contact = {
      name,
      email,
      resourceSlug,
    };

    const payload = DownloadResourceForm.safeParse(contact);

    if (!payload.success) {
      log.ingest({
        event: "validation error",
        data: payload.error,
        status_log: STATUS_LOG.error,
      });

      return {
        success: false,
        error: payload.error,
      };
    }

    log.ingest({
      event: "validation success",
      data: contact,
      status_log: STATUS_LOG.success,
    });

    // fetch resource by resourceId sanitized
    const resource = await loadResource(resourceSlug);

    if (!resource.data) {
      log.ingest({
        event: "resource not found",
        data: contact,
        status_log: STATUS_LOG.error,
      });

      return {
        success: false,
        error: "Resource not found",
      };
    }

    log.ingest({
      event: "resource found",
      data: resource.data,
      status_log: STATUS_LOG.success,
    });

    const sheet = await getOrCreateSheet("Resource " + resource.data?.title);

    log.ingest({
      event: "sheet get or create",
      data: contact,
      status_log: STATUS_LOG.success,
    });

    const foundContact = await findContact(sheet, payload.data.email);

    if (foundContact) {
      log.ingest({
        event: "contact found",
        data: foundContact.toObject(),
        status_log: STATUS_LOG.success,
      });

      // Ovewrite contact
      foundContact.assign(mapContact(contact));

      await foundContact.save();

      log.ingest({
        event: "contact updated",
        data: foundContact.toObject(),
        status_log: STATUS_LOG.success,
      });

      return {
        success: true,
        url: resource.data?.resource,
        error: null,
      };
    }

    await sheet.addRow(mapContact(contact));

    log.ingest({
      event: "resource downloaded",
      data: contact,
      status_log: STATUS_LOG.success,
    });

    return {
      success: true,
      url: resource.data?.resource,
      error: null,
    };
  } catch (error) {
    log.ingest({
      event: "error",
      data: error.message,
      status_log: STATUS_LOG.error,
    });

    return {
      success: false,
      error: error.message,
    };
  }
}
